# Generated by Django 4.1.1 on 2022-09-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='html',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='html',
        ),
    ]
